/* Region / Reposts / Stories all need data that TikTok only serves to a
 * signed request (`X-Bogus`), and that signature is generated by TikTok's
 * own obfuscated client JS. Rather than reimplementing that (fragile, goes
 * stale fast), we drive a real headless Chromium via Cloudflare's Browser
 * Rendering product and let TikTok's own page sign its own requests, then
 * read the results back out. This is inherently slower (real navigation +
 * render) and best-effort: if TikTok doesn't expose a piece of data to a
 * logged-out session at all — which region and stories often aren't — no
 * amount of browser automation gets it back, and we report "unavailable"
 * rather than fabricate something.
 *
 * NOTE: the exact DOM structure / selectors below are TikTok's current
 * (2026) web app and can drift. If a route below starts always coming back
 * "unavailable", check with `wrangler dev --remote` first — TikTok's markup
 * or its network calls may have changed. */

import puppeteer, { type BrowserWorker } from "@cloudflare/puppeteer";
import { TIKTOK_UA } from "../tiktokPage";

export interface Env {
  BROWSER: BrowserWorker;
  ALLOWED_ORIGIN: string;
}

const NAV_TIMEOUT_MS = 20_000;

async function withPage<T>(
  env: Env,
  fn: (page: import("@cloudflare/puppeteer").Page) => Promise<T>,
): Promise<T> {
  const browser = await puppeteer.launch(env.BROWSER);
  try {
    const page = await browser.newPage();
    await page.setUserAgent(TIKTOK_UA);
    await page.setViewport({ width: 1280, height: 900 });
    page.setDefaultNavigationTimeout(NAV_TIMEOUT_MS);
    return await fn(page);
  } finally {
    await browser.close();
  }
}

/** Collects JSON bodies of XHR/fetch responses from TikTok's API while a
 *  page action runs, so we can read data TikTok only sends after its own
 *  JS signs the request. */
function collectApiResponses(
  page: import("@cloudflare/puppeteer").Page,
  urlIncludes: string,
) {
  const bodies: unknown[] = [];
  const listener = async (res: import("@cloudflare/puppeteer").HTTPResponse) => {
    if (!res.url().includes(urlIncludes)) return;
    try {
      bodies.push(await res.json());
    } catch {
      // Not JSON (or body already consumed) — ignore.
    }
  };
  page.on("response", listener);
  return {
    bodies,
    stop: () => page.off("response", listener),
  };
}

export interface RegionResult {
  region: string | null;
  available: boolean;
  message: string | null;
}

export async function getRegion(env: Env, username: string): Promise<RegionResult> {
  return withPage(env, async (page) => {
    const { bodies, stop } = collectApiResponses(page, "/api/user/detail");
    await page.goto(`https://www.tiktok.com/@${encodeURIComponent(username)}`, {
      waitUntil: "networkidle0",
    });
    stop();

    // Try the network-captured responses first (these come from TikTok's own
    // signed client-side fetch, which sometimes carries `region` even when
    // the server-rendered HTML doesn't).
    for (const body of bodies) {
      const region = (body as { userInfo?: { user?: { region?: string } } })
        ?.userInfo?.user?.region;
      if (region) return { region, available: true, message: null };
    }

    // Fall back to whatever hydrated into the page's own state.
    const region = await page
      .evaluate(() => {
        const w = window as unknown as {
          __UNIVERSAL_DATA_FOR_REHYDRATION__?: {
            __DEFAULT_SCOPE__?: {
              "webapp.user-detail"?: { userInfo?: { user?: { region?: string } } };
            };
          };
        };
        return (
          w.__UNIVERSAL_DATA_FOR_REHYDRATION__?.__DEFAULT_SCOPE__?.[
            "webapp.user-detail"
          ]?.userInfo?.user?.region ?? null
        );
      })
      .catch(() => null);

    if (region) return { region, available: true, message: null };
    return {
      region: null,
      available: false,
      message: "TikTok doesn't expose region for this account without an authenticated session.",
    };
  });
}

interface RawPost {
  id: string;
  desc: string;
  video?: { cover?: string; dynamicCover?: string };
  author?: { uniqueId?: string };
}

export interface RepostItem {
  id: string;
  desc: string;
  cover: string;
  url: string;
}

export interface RepostsResult {
  items: RepostItem[];
  available: boolean;
  message: string | null;
}

function itemsFromBodies(bodies: unknown[]): RawPost[] {
  const items: RawPost[] = [];
  for (const body of bodies) {
    const list = (body as { itemList?: RawPost[] })?.itemList;
    if (Array.isArray(list)) items.push(...list);
  }
  return items;
}

export async function getReposts(env: Env, username: string): Promise<RepostsResult> {
  return withPage(env, async (page) => {
    const { bodies, stop } = collectApiResponses(page, "/api/post/item_list");
    await page.goto(`https://www.tiktok.com/@${encodeURIComponent(username)}`, {
      waitUntil: "networkidle0",
    });

    // The "Reposts" tab only exists in the DOM for accounts with public
    // reposts. TikTok's own client-side router loads them on click.
    const clicked = await page
      .evaluate(() => {
        const tabs = Array.from(document.querySelectorAll('[role="tab"], a, div'));
        const repostTab = tabs.find((el) =>
          (el.textContent ?? "").trim().toLowerCase() === "reposts",
        ) as HTMLElement | undefined;
        repostTab?.click();
        return Boolean(repostTab);
      })
      .catch(() => false);

    if (!clicked) {
      stop();
      return {
        items: [],
        available: false,
        message: "This account has no visible Reposts tab.",
      };
    }

    await page
      .waitForResponse((res) => res.url().includes("/api/post/item_list"), {
        timeout: 10_000,
      })
      .catch(() => null);
    stop();

    const raw = itemsFromBodies(bodies);
    const items: RepostItem[] = raw
      .filter((item) => item.author?.uniqueId && item.author.uniqueId !== username)
      .map((item) => ({
        id: item.id,
        desc: item.desc ?? "",
        cover: item.video?.dynamicCover ?? item.video?.cover ?? "",
        url: `https://www.tiktok.com/@${item.author?.uniqueId}/video/${item.id}`,
      }));

    return {
      items,
      available: true,
      message: items.length === 0 ? "No reposts found." : null,
    };
  });
}

export interface StoryItem {
  id: string;
  cover: string;
}

export interface StoriesResult {
  items: StoryItem[];
  available: boolean;
  message: string | null;
}

export async function getStories(env: Env, username: string): Promise<StoriesResult> {
  return withPage(env, async (page) => {
    const { bodies, stop } = collectApiResponses(page, "story");
    await page.goto(`https://www.tiktok.com/@${encodeURIComponent(username)}`, {
      waitUntil: "networkidle0",
    });
    stop();

    const raw = itemsFromBodies(bodies) as unknown as {
      id: string;
      video?: { cover?: string };
    }[];

    if (raw.length === 0) {
      return {
        items: [],
        available: false,
        message: "No active stories, or unavailable without a logged-in session.",
      };
    }

    return {
      items: raw.map((s) => ({ id: s.id, cover: s.video?.cover ?? "" })),
      available: true,
      message: null,
    };
  });
}
